test_root:
    max_points: 4.0
    initial_steps: 
        - create_email_server:
            name: "server-1"
            port: 9999
    test_suites: 
        - test_suite:
            name: "Zakladní test odesílání Emailů"
            delay: 500
            test_cases: 
                - test_case:
                    name: "Test odeslání emailu"
                    description: "Testuje se odeslání jednoho e-mailu. Samotný obsah odeslaného emailu nebude nijak ověřován, pouze se testuje, zda dorazil na server."
                    steps: 
                        # spusti testovanou aplikaci
                        - run_app: "java -jar app/build/libs/app.jar localhost 9999 sender@email.com recipient@email.com Subject1 'Text Message'"
                        # ceka na prijeti emailu
                        - wait_until:
                            module_name: "server-1"
                            time_out: 5000
                        # overi zda byl prijat 1 email
                        - count_and_store:
                            var_name: "var-1"
                            module_name: "server-1"
                        - assert_equals:
                            var_name: "var-1"
                            value: 1
                        - wait: 500
                - test_case:
                    name: "Test obsahu emailu 1"
                    description: "Testuje se odeslání jednoho e-mailu. Po přijetí emailu je ověřován i jeho obsah."
                    steps: 
                        # spusti testovanou aplikaci
                        - run_app: "java -jar app/build/libs/app.jar localhost 9999 sender@email.com recipient@email.com Subject1 'Text Message'"
                        # ceka na prijeti emailu
                        - wait_until:
                            module_name: "server-1"
                            time_out: 5000
                        # overi obsah predmetu a obsahu email
                        - store_to_var:
                            var_name: "var-1"
                            module_name: "server-1"
                            tag: "Subject1"
                            mode: "equals"
                        - assert_string:
                            var_name: "var-1"
                            expected: "Text Message"
                            mode: "equals"
                            case_sensitive: true
                        - wait: 500
                - test_case:
                    name: "Test odeslání neplatného emailu"
                    description: "Prostřednictvím testované aplikace je odeslán email s neplatnými údaji. Předpokládá se, že email nebude odeslán."
                    steps: 
                        # spusti testovanou aplikaci
                        - run_app: "java -jar app/build/libs/app.jar localhost 9999 sender@email.com recipient@email.com"
                        - wait: 3000
                        # overi zda neprisel zadny email
                        - count_and_store:
                            var_name: "var-1"
                            module_name: "server-1"
                        - assert_equals:
                            var_name: "var-1"
                            value: 0
                        - wait: 500
