name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: ~/.gradle
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build with Gradle
      run: ./gradlew build

    - name: Save build artifacts
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: app-libs
        path: app/build/libs/*.jar

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Set up JDK 17 
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: app-libs
        path: app/build/libs

    - name: Run black box tests
      run: java -jar NATT.jar -c test-config.yaml

    - name: Save test report
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: test_report.html