test_root:
    max_points: 10.0
    initial_steps: 
        - run_app: 
            command: "java -jar echo_test.jar"
            name: "app-1"
        - wait: 500
    test_suites: 
        - test_suite:
            name: "Suite name 1"
            delay: 500
            initial_steps: []
            test_cases: 
                - test_case:
                    name: "Case name 1"
                    description: "Description 1 here"
                    steps: 
                        - module_send:
                            name: "app-1"
                            message: "Message $your-var"
                            delay: 100
                        - wait: 3000
                - test_case:
                    name: "Case name 2"
                    description: "Description 2 here"
                    steps:
                        - standard_stream_send: 
                            message: "Message to send"
                            name: "app-1"